# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/umidigi/A5_Pro/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/umidigi/A5_Pro

PRODUCT_COPY_FILES += \
    vendor/umidigi/A5_Pro/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/umidigi/A5_Pro/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    vendor/umidigi/A5_Pro/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
    vendor/umidigi/A5_Pro/proprietary/etc/init/kpoc_charger.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/kpoc_charger.rc \
    vendor/umidigi/A5_Pro/proprietary/etc/permissions/privapp-permissions-mediatek.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-mediatek.xml \
    vendor/umidigi/A5_Pro/proprietary/etc/permissions/com.mediatek.ims.plugin.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.mediatek.ims.plugin.xml \
    vendor/umidigi/A5_Pro/proprietary/etc/permissions/com.mediatek.op.ims.common.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.mediatek.op.ims.common.xml \
    vendor/umidigi/A5_Pro/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libshowlogo.so \
    vendor/umidigi/A5_Pro/proprietary/lib/libsysenv_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsysenv_system.so \
    vendor/umidigi/A5_Pro/proprietary/product/vendor_overlay/28/lib/libmtk-ril.so:$(TARGET_COPY_OUT_SYSTEM)/vendor_overlay/28/lib/libmtk-ril.so

PRODUCT_PACKAGES += \
    ImsService