# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/umidigi/A5_Pro/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/umidigi/A5_Pro

PRODUCT_COPY_FILES += \
    vendor/umidigi/A5_Pro/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/umidigi/A5_Pro/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so
